// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class BacteriaFactory : MonoBehaviour
	{
		public GameObject bacteria_prefab;
		public Aggressor aggressor;

		public void Start() {
			if (bacteria_prefab == null) {
				throw new ArgumentNullException();
			}
			if (aggressor == null) {
				throw new ArgumentNullException();
			}
			aggressor.ShootBacteria += OnCreateBacteriaRequested;
		}

		public void Update() {

		}

		public BacteriaFactory ()
		{

		}


		void OnCreateBacteriaRequested (object sender, EventArgs e)
		{
			var bacteria = ((GameObject)Instantiate (bacteria_prefab)).GetComponent<Bacteria> ();

			if (bacteria == null) {
				throw new ArgumentNullException();			
			}

			bacteria.transform.position = aggressor.transform.position;
			bacteria.Velocity = (aggressor.transform.position - new Vector3 (0, 0, 0)) * -1;
			bacteria.Velocity.Normalize ();
		}
	}
}

