// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class Utils
	{
		public static readonly Vector3 UP = new Vector3(0,1,0);
		public static readonly Vector3 DOWN = new Vector3(0,-1,0);
		public static readonly Vector3 RIGHT = new Vector3(1,0,0);
		public static readonly Vector3 LEFT = new Vector3(-1,0,0);

	}
}

